# WARNING: This configuration is meant for development/testing, do not use for production

version: '3.9'

services:
  db:
    image: mariadb:10
    ports:
      - 3306:3306
    environment:
      - MARIADB_ROOT_PASSWORD=password
      - MARIADB_DATABASE=test
      - MARIADB_USER=test-user
      - MARIADB_PASSWORD=password
    networks:
      - providence
    healthcheck:
      test: 'mariadb-admin --password="$$MARIADB_PASSWORD" --silent ping'
      interval: 5s
      timeout: 5s
      retries: 4

  providence:
    build:
      context: .
    depends_on:
      - db
    ports:
      - 8080:80
    environment:
      - INIT_DB=false
      - DB_ROOT_PASSWORD=password
      - CA_DB_HOST=db
      - CA_DB_USER=providence-user
      - CA_DB_PASSWORD=password
      - CA_DB_DATABASE=providence
      - ENSURE_PERMISSIONS=false
      - CA_DB_TYPE=mysqli
      - CA_OUT_OF_PROCESS_SEARCH_INDEXING_PORT=80
      - CA_OUT_OF_PROCESS_SEARCH_INDEXING_PROTOCOL=tcp
      - CA_OUT_OF_PROCESS_SEARCH_INDEXING_HOSTNAME=localhost
    volumes:
      - ./entrypoint.sh:/entrypoint.sh
      - ./providence-setup.php:/var/www/setup.php
      - ./volumes/providence-config:/var/www/app/conf
      - ./volumes/media:/var/www/media
    networks:
      - providence

networks:
  providence: