version: '3.9'

services:
  db:
    image: mariadb:10
    ports:
      - 3306:3306
    environment:
      - MARIADB_ROOT_PASSWORD=password
      - MARIADB_DATABASE=test
      - MARIADB_USER=test-user
      - MARIADB_PASSWORD=password
    networks:
      - providence

  providence:
    build:
      context: .
    depends_on:
      - db
    ports:
      - 8080:80
    environment:
      - DB_ROOT_PASSWORD=password
      - CA_DB_HOST=db
      - CA_DB_USER=providence-user
      - CA_DB_PASSWORD=password
      - CA_DB_DATABASE=providence
    volumes:
      - ./entrypoint.sh:/entrypoint.sh
      - ./providence-setup.php:/var/www/setup.php
      - ./volumes/providence-config:/var/www/app/conf
      - ./volumes/media:/var/www/media
    networks:
      - providence

networks:
  providence: