version: '3.9'

services:
  db:
    image: mysql:8-oracle
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=test
      - MYSQL_USER=test-user
      - MYSQL_PASSWORD=password
    networks:
      - providence

  providence:
    build:
      context: .
    depends_on:
      - db
    ports:
      - 8080:80
    environment:
      - DB_ROOT_PASSWORD=password
      - CA_DB_HOST=db
      - CA_DB_USER=providence-user
      - CA_DB_PASSWORD=password
      - CA_DB_DATABASE=providence
    volumes:
      - ./entrypoint.sh:/entrypoint.sh
      - ./providence-setup.php:/var/www/setup.php
      # - ./volumes/providence-config:/var/www/providence/app/conf
      # - ./volumes/media:/var/www/providence/media/
      # - /volumes/pawtucket-config:/var/www/app/conf
    networks:
      - providence

networks:
  providence: