version: '3.9'

services:
  db:
    image: mysql:8-oracle
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=test
      - MYSQL_USER=test-user
      - MYSQL_PASSWORD=password
    networks:
      - providence

  providence:
    build:
      context: .
    depends_on:
      - db
    ports:
      - 8080:80
    environment:
      - DB_USER=providence-user
      - DB_PW=password
      - DB_NAME=providence
      - DB_HOST=db
      - DB_ROOT_PASSWORD=password
    volumes:
      - ./entrypoint.sh:/entrypoint.sh
      # - ./volumes/providence-config:/var/www/providence/app/conf
      # - ./volumes/media:/var/www/providence/media/
      # - /volumes/pawtucket-config:/var/www/app/conf
    networks:
      - providence

networks:
  providence: