version: '3.9'

services:
  db:
    image: mysql:8-oracle
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=test
      - MYSQL_USER=test-user
      - MYSQL_PASSWORD=password
    networks:
      - providence

  providence:
    build:
      context: .
    entrypoint: "/bin/bash"
    depends_on:
      - db
    ports:
      - 8080:80
    environment:
      - DB_USER=providence-user
      - DB_PW=password
      - DB_NAME=providence
      - DB_HOST=db
      - DB_ROOT_PASSWORD=password
    networks:
      - providence
    volumes:
      - ./entrypoint.sh:/entrypoint.sh

networks:
  providence: