name: Build and push

on:
  push:
    tags: '*'
    branches:
      - main
  pull_request:

jobs:
  build-and-push:
    name: Build & push
    runs-on: ubuntu-latest
    timeout-minutes: 60

    permissions:
      contents: read
      id-token: write
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GitHub container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: linux/amd64, linux/arm64/v8

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker metadata
        id: docker_metadata
        uses: docker/metadata-action@v5
        with:
          images: |
            tofran/providence
            ghcr.io/tofran/providence
          tags: |
            type=sha
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}@${{ github.run_id }}
            type=semver,pattern={{major}}.{{minor}}@${{ github.run_id }}
            type=semver,pattern={{major}}@${{ github.run_id }}
            type=semver,pattern={{version}}@${{ github.sha }}
            type=semver,pattern={{major}}.{{minor}}@${{ github.sha }}
            type=semver,pattern={{major}}@${{ github.sha }}
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
          flavor: |
            latest=${{ github.ref_type == 'tag' }}

      - name: Build and push (tagged version)
        if: github.ref_type == 'tag'
        uses: docker/build-push-action@v5
        with:
          context: ./
          file: ./Dockerfile
          platforms: linux/amd64, linux/arm64/v8
          tags: ${{ steps.docker_metadata.outputs.tags }}
          labels: ${{ steps.docker_metadata.outputs.labels }}
          build-args:
            CA_PROVIDENCE_VERSION=${{ github.ref_name }}
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build and push (all other builds)
        if: github.ref_type != 'tag'
        uses: docker/build-push-action@v5
        with:
          context: ./
          file: ./Dockerfile
          platforms: linux/amd64, linux/arm64/v8
          tags: ${{ steps.docker_metadata.outputs.tags }}
          labels: ${{ steps.docker_metadata.outputs.labels }}
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
